### ISSUE TITLE
Add `download-examples` CLI command to setup.py for getting all notebook

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#240]
We want to be able to do this:

```
$> xrspatial download-examples
```

Exactly like datashader

- [x] Pharmacy Deserts ( https://github.com/makepath/xarray-spatial/blob/master/examples/pharmacy-deserts.ipynb)
- [x] Store example datasets in Public / Anonymous Read Azure Bucket

**Comment by jbednar** [comment]
Note that Datashader and other HoloViz projects provide `copy_examples` (copy the examples from where they are stashed in the python directory into the user's cwd), `fetch_data` (which typically downloads the data), and `examples` (which invokes both `copy_examples` and `fetch_data`).  So if you want it to be comparable to how Datashader does it (so that you can easily give users instructions for both), what you're discussing here appears to be `fetch_data`, not being about examples (which for Datashader are notebooks, not datasets).

**Comment by lex-c** [comment]
Done, but with notes for additional work needed. 'copy-examples', 'fetch-data', and 'examples' commands work. It is not attached to an azure bucket yet, because I still need access to that, as well as to the pharmacy location data source, but I tested it with a sample dataset from Kaggle and an aws bucket.

**Comment by giancastro** [comment]
@lex-c, has this issue already solved?
