### ISSUE TITLE
Add additional badges like those in Bokeh

### ISSUE THREAD

**Issue by brendancol** [makepath/xarray-spatial#459]
![image](https://user-images.githubusercontent.com/433221/120815085-22935c80-c515-11eb-9ad2-07fa333ba703.png)

**Comment by thuydotm** [comment]
Bokeh itself has removed the Static Analysis Badges. The new contributor badge has been added since commit https://github.com/bokeh/bokeh/commit/ef313c52105f5e9cc58ef02623df8f4f8ebdfa12. I think it's a good idea to use the similar badge for xarray-spatial contributors so that we can safely remove list of contributors in README.md as it's quite long now and could be even longer in the future. People can still see who contributes to the library from the right side view of the GitHub repo https://github.com/makepath/xarray-spatial/graphs/contributors
