### ISSUE TITLE
Compat error with `numpy>1.20`

### ISSUE THREAD

**Issue by darribas** [makepath/xarray-spatial#565]
**Describe the bug**
Cannot install the latest version of `xarray-spatial` with an up-to-date stack (`numpy>1.20`).

**Expected behavior**
Install the latest version of `xarray-spatial` through conda

**Screenshots**
I'm trying to update the [`gds_env`](https://github.com/darribas/gds_env) and trying an install that pins `xarray-spatial` to its latest release returns the following error:

```
package xarray-spatial-0.2.9-pyhd8ed1ab_0 requires numpy >=1.7,<=1.20, but none of the providers can be installed
```
The `numpy` version it is installing (for compatibility with other libraries) is 1.21.2. Is there any reason why it pins to 1.20 as the most recent version?

**Comment by ianthomas23** [comment]
@darribas My earlier answer was wrong. It turns out that we do need to pin numpy to <=1.20 as that is what numba 0.54.x requires. This restriction has been removed in numba's master branch, so we will need to wait until their next release.  I don't think will be long, they are finishing off their python 3.10 support and I expect a release after that.

**Comment by girgink** [comment]
If this limitation is coming from `numba`, isn't it better to let `pip` handle this? By manually setting the upper limit you prevent automatic version handling and block upgrade even it is possible.

**Comment by ianthomas23** [comment]
Yes, I agree.
