### ISSUE TITLE
Cannot run zonal stats with Dask with NumPy backed DataArray

### ISSUE THREAD

**Issue by tselea** [makepath/xarray-spatial#701]
**Describe the bug**
Attempting to run the example with zonal stats, using Dask Xarrays as in here: 
https://xarray-spatial.org/v0.3.2/reference/_autosummary/xrspatial.zonal.stats.html

But I get an Assertion Error from Dask. I think it's a problem with my conda environment. 
Could you please help me to run the example properly? Thank you in advance.

**Expected behavior**
Run the zonal stats with Dask and get the result as in example docs.

**Screenshots**
<img width="1059" alt="Screenshot 2022-05-03 at 22 30 14" src="https://user-images.githubusercontent.com/14962659/166555128-36772543-755e-42fe-9f09-fcaffcfcb152.png">
<img width="1062" alt="Screenshot 2022-05-03 at 22 30 22" src="https://user-images.githubusercontent.com/14962659/166555138-7bd932d0-864d-4ebe-bdea-82677573627a.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur (version 11.6)
 - Browser opera / jupyter lab

**Additional context**
From my conda environment:
python=3.8.13
xarray-spatial=0.3.3

**Comment by thuydotm** [comment]
Thanks for raising this. I checked the example and found out that the issue was in the way Dask arrays (`zones_dask` and `values_dask`) were created. 

`zones` has already created as a xarray data array so if we do 
```
zones_dask = xr.DataArray(da.from_array(zones, chunks=(3, 3)))
```
then `zones_dask` is not a numpy backed Dask data array. (see type of each chunk is a `xarray.core.dataarray.DataArray`)
![image](https://user-images.githubusercontent.com/47617499/166626815-4fa42918-2865-4873-bb19-869e098f73da.png)


The function should work well with Dask with NumPy-backed data array. Can you try out this new code? I'll push a fix for this shortly.
```
values_dask = da.from_array(values_data, chunks=(3, 3))
zones_dask = da.from_array(zones_data, chunks=(3, 3))
```
![image](https://user-images.githubusercontent.com/47617499/166627004-9f72298c-ebbf-4eb6-93f7-ce615e3fac54.png)

**Comment by tselea** [comment]
Thank you for your reply! I managed to make it work using your advice. 
Thanks for the help!

So I created a dask-array from numpy, then wrapped it using xarray, as follows:

`values_dask = xr.DataArray(da.from_array(values_data, chunks=(3, 3)))
zones_dask = xr.DataArray(da.from_array(zones_data, chunks=(3, 3)))
`
